### ISSUE TITLE
MS-style inline assembly is not available. Unable to find target for this triple (no targets are registered).

### ISSUE THREAD

**Issue by pavledev** [Viladoman/StructLayout#21]
When I right click on class name and press Show Struct Layout I get this error: MS-style inline assembly is not available. Unable to find target for this triple (no targets are registered).
https://imgur.com/Of08Imx
Can you please fix this?

**Comment by Viladoman** [comment]
Hey! Thanks for letting me know! 
I will have a look once I have some free time. I will keep you updated.

**Comment by Viladoman** [comment]
Hi! Happy new year! I added the native platform initialization to the clang parser in order to avoid having those target errors. 

Could you please try this version: [StructLayout.zip](https://github.com/Viladoman/StructLayout/files/5759356/StructLayout.zip)

Let me know if the issue is still present. Sadly this change doubles the size of the dll. 

Thanks.

**Comment by pavledev** [comment]
@Viladoman Hi and Happy New Year.
I tested it now and it's working. I don't get error for inline assembly anymore.
Thank you very much.
